# Generated by Django 4.2.7 on 2023-11-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(default='TuValorModeloPredeterminado', max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
